---
title: Tables and figures
subtitle: "Revisiting the Early Aurignacian in Italy: New Insights from Grotta della Cala"
author: 
- Armando Falcucci, Keiko Kitagawa, Luc Doyon, Laura Tassoni, Tom Higham, Clarissa Dominici, Diego Dreossi, Jacopo Crezzini, Matteo Rossini, Stefano Benazzi, Ivan Martini, Francesco Boschin, Vincenzo Spagnolo, Adriana Moroni
- armando.falcucci@uni-tuebingen.de & vincenzo.spagnolo@unisi.it (corresponding authors)
date: ''
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "../output"
    )
  })
output: 
  html_document:
    toc: true
    toc_float: true
---

    Foreword: Only figures built with R are reported in this file. The other figures are accessible in the output folder `figures`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r include=FALSE}
library(readxl)
library(knitr)
library(kableExtra)
library(dplyr)
library(tidyr)
library(janitor)
library(forcats)
library(rstatix)
library(tidyverse)
library(MetBrewer)
library(plyr)
library(forcats)
library(scales)
library(cowplot)
library(ggpubr)
library(extrafont)
library(patchwork)

Dataset <- readr::read_csv(file = "../data/Ca_Dataset_complete.csv", col_names = TRUE,
                           col_types = readr::cols(
                             `Sub-layer` = readr::col_factor(levels = c("AU10", "AU11", "AU12", "AU13")
                           )))

Dataset_cores <- readr::read_csv(file = "../data/Ca_Dataset_cores.csv", col_names = TRUE,
                           col_types = readr::cols(
                             `Sub-layer` = readr::col_factor(levels = c("AU10", "AU11", "AU12", "AU13")
                           )))

comparison <- list(c("AU13", "AU12"), c("AU13", "AU11"), c("AU13", "AU10"), c("AU12", "AU11"), c("AU12", "AU10"), c("AU11", "AU10"))
```

## Tables

### Table 1

```{r, echo=FALSE, warning=FALSE}
Dataset %>%
  mutate(Class = fct_relevel(Class, "Core", "Core-Tool", "Blank", "Tool", "Pebble")) %>%
  arrange(Class) %>%
  tabyl(`Sub-layer`, Class) %>%
  adorn_totals("col") %>%
  adorn_totals("row") %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  adorn_title(placement = "top") %>%
  kbl(align = "lcccccr") %>%
  kable_classic(full_width = F)
```

### Table 2

```{r, echo=FALSE, warning=FALSE}
Dataset %>%
  filter(Class == "Tool" | Class == "Core-Tool") %>%
  tabyl(Typology.new, `Sub-layer`) %>%
  adorn_totals("row") %>%
  adorn_totals("col") %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  adorn_title(placement = "top") %>%
  kbl(align = "lccccr") %>%
  kable_classic_2(lightable_options = "striped", full_width = F)
```
  **Table 2** General overview of the main tool categories recovered across the studied sequence with rounded percentages in brackets. Undet. stands for Undetermined.

### Table 3

```{r, echo=FALSE, warning=FALSE}
Dataset_cores %>%
  filter(Laminar_y.n == "yes") %>%
  mutate(Core.classification.3 = fct_relevel(Core.classification.3, "Initial", "Carinated endscraper", "Carinated core", "Carinated burin", "Burin core", "Narrow-sided", "Semi-circumferential", "Wide-faced", "Multi-platform", "Shatter laminar")) %>%
  tabyl(Core.classification.3, `Sub-layer`) %>%
  adorn_totals("row") %>%
  adorn_totals("col") %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  adorn_title(placement = "top") %>%
  kbl(align = "lccccr") %>%
  kable_classic_2(lightable_options = "striped", full_width = F)
```

### Table 4

```{r, echo=FALSE, warning=FALSE}
Dataset_cores %>%
  filter(Laminar_y.n == "no") %>%
  mutate(Core.classification.3 = recode(Core.classification.3, Discoid = "Inclined")) %>%
  mutate(Core.classification.3 = fct_relevel(Core.classification.3, "Bipolar", "Multidirectional", "Platform flake", "Parallel", "Inclined", "Shatter", "Tested")) %>%
  tabyl(Core.classification.3, `Sub-layer`) %>%
  adorn_totals("row") %>%
  adorn_totals("col") %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  adorn_title(placement = "top") %>%
  kbl(align = "lccccr") %>%
  kable_classic_2(lightable_options = "striped", full_width = F)
```

## Figures

### Figure 7

```{r, echo=FALSE, warning=FALSE, include=FALSE}
bladelets_complete <- Dataset %>%
  filter(Blank == "Bladelet" | Blank == "Flakelet",
         Preservation == "Complete") %>%
  select(ID, `Sub-layer`, Class, Length) %>%
  mutate(Class = recode(Class, Blank = "Bladelet", Tool = "Bladelet"))


flak_surf_lenght_carinated <- Dataset_cores %>%
  filter(Core.classification == "Carinated") %>%
  select(ID, `Sub-layer`, Core.classification, Flaking.surface.length) %>%
  dplyr::rename(Class = Core.classification, Length = Flaking.surface.length)

flak_surf_lenght_platform <- Dataset_cores %>%
  filter(Core.classification != "Carinated", Laminar_y.n == "yes", Core.classification != "Shatter laminar") %>%
  select(ID, `Sub-layer`, Core.classification, Flaking.surface.length) %>%
  dplyr::rename(Class = Core.classification, Length = Flaking.surface.length) %>%
  mutate(Class = recode(Class, Initial = "Platform", `Narrow-sided` = "Platform", `Burin core` = "Platform", `Wide-faced` = "Platform", `Semi-circumferential` = "Platform", `Multi-platform` = "Platform"))

```
```{r, echo=FALSE, warning=FALSE, include=FALSE}
comparison_bladelet_carinated <- full_join(bladelets_complete, flak_surf_lenght_carinated)
comparison_bladelet_carinated <- full_join(comparison_bladelet_carinated, flak_surf_lenght_platform)
```
```{r, echo=FALSE, warning=FALSE, fig.align='center'}
comparison_bladelet_carinated.fig <- comparison_bladelet_carinated %>%
  ggplot(aes(x = `Sub-layer`, y = Length)) +
  geom_boxplot(aes(fill = Class), alpha = 0.7) +  # Boxplot with alpha transparency
  scale_fill_manual(labels = c("Bladelet (n = 417)", "Carinated core (n = 112)", "Platform core (n = 30)"), 
                    values = c("#1f77b4", "#9467bd", "#8c564b")) +  # Boxplot colors
  scale_color_manual(values = c("#1f77b4", "#9467bd", "#8c564b")) +  # Jitter points use the same colors
    ggthemes::theme_clean() +
  theme(text = element_text(family = "Times New Roman", size = 18), 
        axis.text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(family = "Times New Roman", size = 14),
        legend.position = "none") +
  guides(fill = guide_legend(title = NULL)) +
  labs(y = "Length (mm)") +
  theme(legend.position = "bottom")

# # Save the plot
# ggsave("../output/figures/Figure_7.tiff", plot = comparison_bladelet_carinated.fig, width = 8, height = 4, units = "in", dpi = 300)
```


```{r, echo=FALSE, warning=FALSE, fig.align='center'}

# Bladelet Length Plot (Single Color)
bladelet.length <- Dataset %>%
  filter(Blank == "Bladelet" | Blank == "Flakelet",
         Preservation == "Complete",
         Class == "Blank") %>%
  group_by(`Sub-layer`) %>%
  ggplot(aes(x = `Sub-layer`, y = Length)) +
  geom_boxplot(fill = "#1f77b4", alpha = 0.7) +  # Use a muted blue for the boxplot
  stat_compare_means(label.y = 40.5, label.x = 1.2) +
  geom_jitter(shape = 16, position = position_jitter(width = 0.2), color = "#1f77b4", alpha = 0.5, size = 0.7) +  # Same color as boxplot
  ggthemes::theme_clean() +
  theme(text = element_text(family = "Times New Roman", size = 18), 
        axis.text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(family = "Times New Roman", size = 14),
        legend.position = "none") +
  labs(y = "Length (mm)")

# Bladelet Width Plot (Single Color)
bladelet.width <- Dataset %>%
  filter(Blank == "Bladelet" | Blank == "Flakelet",
         Preservation == "Complete",
         Class == "Blank") %>%
  group_by(`Sub-layer`) %>%
  ggplot(aes(x = `Sub-layer`, y = Width)) +
  geom_boxplot(fill = "#ff7f0e", alpha = 0.7) +  # Use muted orange for the boxplot
  stat_compare_means(label.y = 13, label.x = 1.2) +
  geom_jitter(shape = 16, position = position_jitter(width = 0.2), color = "#ff7f0e", alpha = 0.5, size = 0.7) +  # Same color as boxplot
  ggthemes::theme_clean() +
  theme(text = element_text(family = "Times New Roman", size = 18), 
        axis.text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(family = "Times New Roman", size = 14),
        legend.position = "none") +
  labs(y = "Width (mm)")

# Bladelet Thickness Plot (Single Color)
bladelet.thickness <- Dataset %>%
  filter(Blank == "Bladelet" | Blank == "Flakelet",
         Preservation == "Complete",
         Class == "Blank") %>%
  group_by(`Sub-layer`) %>%
  ggplot(aes(x = `Sub-layer`, y = Thickness)) +
  geom_boxplot(fill = "#2ca02c", alpha = 0.7) +  # Use muted green for the boxplot
  stat_compare_means(label.y = 10, label.x = 1.2) +
  geom_jitter(shape = 16, position = position_jitter(width = 0.2), color = "#2ca02c", alpha = 0.5, size = 0.7) +  # Same color as boxplot
  ggthemes::theme_clean() +
  theme(text = element_text(family = "Times New Roman", size = 18), 
        axis.text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(family = "Times New Roman", size = 14),
        legend.position = "none") +
  labs(y = "Thickness (mm)")


# Combine the plots with manual labels using patchwork syntax
Figure_7 <- (comparison_bladelet_carinated.fig) / 
            (bladelet.length + bladelet.width + bladelet.thickness)

Figure_7

ggsave("../output/figures/Figure_7.tiff", plot = Figure_7, width = 10, height = 7.5, units = "in", dpi = 300)
```